### ISSUE TITLE
cannot find symbol return locationManager.isLocationEnabled()

### ISSUE THREAD

**Issue by Oga-Emma** [Baseflow/flutter-permission-plugins#15]
## 🐛 Bug Report

error: cannot find symbol
      return locationManager.isLocationEnabled();
                            ^
  symbol:   method isLocationEnabled()
  location: variable locationManager of type LocationManager
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location_permissions:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Version:** 2.0.2

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@Oga-Emma we cannot reproduce this error. I looks like you have an outdated environment. Please make sure you update your IDE and the Gradle build tools.

If you keep on having problems please provide us with some more information:

- Output of `flutter doctor -v`;
- The complete error output of the compiler.
