### ISSUE TITLE
Mismatch in compileSdkVersion in Readme.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Baseflow/flutter-permission-plugins#19]
Make sure you set the compileSdkVersion in your "android/app/build.gradle" file to **28**:
```
android {
 compileSdkVersion 29

 ...
}
```

**Comment by mvanbeusekom** [comment]
@ThinkDigitalSoftware thank you very much for pointing this out. We have updated the "README.md" file to:

"
Make sure you set the compileSdkVersion in your "android/app/build.gradle" file to 28 or higher:
```
android {
 compileSdkVersion 28

 ...
}
```
"
