### ISSUE TITLE
HandlePermissionsRequest after call activity request permission unexpected behavior on Android Q

### ISSUE THREAD

**Issue by ChauNTM** [Baseflow/flutter-permission-plugins#24]
## 🐛 Bug Report

Description:
- Call request permission with LocationPermissionLevel.locationAlways -> user presses Deny
- checkPermissionStatus returns Denied -> call request permission again -> user presses allow why using this app
- checkPermissionStatus returns Denied -> call request permission again -> user presses Keep and don't ask again
- checkPermissionStatus again -> return permission is granted --> wrong

### Expected behavior
- The last time when I call checkPermissionStatus again -> return permission is denied
### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

I debuged and detect that code block below is wrong

```
private void handlePermissionsRequest(String[] permissions, int[] grantResults) {
    if (mResult == null) {
      Log.e(LOG_TAG, "Flutter result object is null.");
      return;
    }

    for (int i = 0; i < permissions.length; i++) {
      if (LocationPermissionsPlugin.isLocationPermission(permissions[i])) {
        @PermissionStatus int permissionStatus = toPermissionStatus(grantResults[i]);

        processResult(permissionStatus);
        return;
      }
    }

    processResult(PERMISSION_STATUS_UNKNOWN);
  }
```

because on Android Q, we have 3 different types of permission, and location permission is only granted if we granted all of those.
I think the code block below is true

```
private void handlePermissionsRequest(String[] permissions, int[] grantResults) {
    if (mResult == null) {
      Log.e(LOG_TAG, "Flutter result object is null.");
      return;
    }

    for (int i = 0; i < permissions.length; i++) {
      if (LocationPermissionsPlugin.isLocationPermission(permissions[i])) {
        @PermissionStatus int permissionStatus = toPermissionStatus(grantResults[i]);
        if (permissionStatus == PERMISSION_STATUS_DENIED) {
          processResult(permissionStatus);
          return;
        }
      }
    }

    processResult(PERMISSION_STATUS_GRANTED);
  }
```

**Comment by ChauNTM** [comment]
Please help me create pull request and fix this issue @mvanbeusekom

**Comment by mvanbeusekom** [comment]
Hi @ChauNTM, we are working on support for AndroidQ permissions for the location services. There is a work in progress pull request (see PR #22) which is related to issue #21.

When this is solved it should also solve your problem. Feel free to contribute though, you can find instructions in our contribution guidelines [here](https://github.com/Baseflow/flutter-permission-plugins/blob/develop/CONTRIBUTING.md).

I will be closing this issue since we are tracking everything related with AndroidQ location permissions in issue #21.
