### ISSUE TITLE
[android] checkPermissionStatus returns PermissionStatus.denied even when not asked for permission

### ISSUE THREAD

**Issue by agordeev** [Baseflow/flutter-permission-plugins#34]
## 🐛 Bug Report

The library doesn't provide an unified API across iOS and Android. 

On iOS, it returns `PermissionStatus.unknown` when not asked for permission. 

On Android, it returns `PermissionStatus.denied`, so it is impossible to say whether we asked for permission and the user declined to grant it, or we didn't ask at all.

### Configuration

**Version:** 2.0.4+1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Yes this is correct, unfortunately this is how permissions are implemented by Android. Google automatically assumes permissions are denied until the user explicitly grants your app permissions. Unlike iOS where permissions are unknown until the user explicitly grants or denies the app permissions. 

Our [permission_handler](https://pub.dev/packages/permission_handler) plugin tries to solve this be keeping a record on the Android device and over a better cross-platform interface.
