### ISSUE TITLE
iOS PermissionLevel enum wrong

### ISSUE THREAD

**Issue by alpha-se** [Baseflow/flutter-permission-plugins#6]
The permission level enum is mixed up:
iOS:
typedef NS_ENUM(int, PermissionLevel) {
  PermissionLevelLocation = 0,
  PermissionLevelLocationAlways,  # == 1
  PermissionLevelLocationWhenInUse, # == 2
};

dart:
enum LocationPermissionLevel {
  location, # == 0
  locationWhenInUse, # == 1
  locationAlways, # == 2
}

**Comment by yunyu** [comment]
@mvanbeusekom Would you mind releasing a new version of `location_permissions` to pub (along with a new version of geolocator which incorporates the updated dependency)?

**Comment by mvanbeusekom** [comment]
@alpha-se, @yunyu, we released new versions of the plugins yesterday:

- location_permissions: 2.0.1
- geolocator: 4.0.3
